apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata:
  name: cart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:orathaipp/nonprod-k8s-manifests.git
    targetRevision: main
    path: dev/pedjeab/cart
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-pedjeab-cart
