apiVersion: batch/v1
kind: Job
metadata:
  name: discord-notify-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: discord-notify
          image: curlimages/curl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "🔔 Sending Discord notification...";
              curl -X POST -H "Content-Type: application/json" \
                -d '{"content": "✅ Kubernetes Job completed successfully!"}' \
                https://discord.com/api/webhooks/1373543677632446475/qLoBlRomiQEMA_e0nxMzpIjblgmoVEYWDVFkRPj-DTXjqEXLCxYP_0O5pju3Nj7zr1tx
      restartPolicy: Never
