apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payment
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payment
    spec:
      containers:
        - image: nginx:1.23
          name: nginx
          resources: {}
status: {}
