apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment
  name: payment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: payment
  type: ClusterIP
status:
  loadBalancer: {}
